development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tmbus_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tmbus_test
  pool: 5



production:
  adapter: postgresql
  encoding: unicode
  database: tmbus_production
  pool: 5
