class Vehicle
  VEHICLE_TYPE_BUS = 11
  VEHICLE_TYPE_TROLLEY = 12
  VEHICLE_TYPE_EXPRESS = 13
  VEHICLE_TYPE_METRO = 13
  VEHICLE_TYPE_TRAM = 21

  VEHICLE_TYPES_LETTERS = {
          VEHICLE_TYPE_BUS => '',
          VEHICLE_TYPE_TROLLEY => 'Tb',
          VEHICLE_TYPE_EXPRESS => 'E',
          VEHICLE_TYPE_METRO => 'M',
          VEHICLE_TYPE_TRAM => 'Tv',
  }


end
